name: Mac2Droid
options:
  bundleIdPrefix: com.grkndev
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  Mac2Droid:
    type: application
    platform: macOS
    sources:
      - path: Mac2Droid
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.grkndev.mac2droid
        INFOPLIST_FILE: Mac2Droid/Info.plist
        CODE_SIGN_ENTITLEMENTS: Mac2Droid/Mac2Droid.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
    entitlements:
      path: Mac2Droid/Mac2Droid.entitlements
      properties:
        com.apple.security.app-sandbox: false
